### ISSUE TITLE
DVM Preprocessing Error: No such file or directory: 'features/dvm_features_train_noOH_all_views_physical_jittered_50.csv'

### ISSUE THREAD

**Issue by carrtesy** [paulhager/MMCL-Tabular-Imaging#10]
Hello,

First of all, thanks for your great work. 

I'd like to ask questions regarding your dvm datasets preprocessing jupyter notebook code.

I works well till "Check transform" cells, but it complains when we try to execute the cell right below. 
<img width="1311" alt="image" src="https://github.com/paulhager/MMCL-Tabular-Imaging/assets/38837579/009ac95f-a3b1-4bde-9800-ea85838c0a6f">

What might be relevant is the cell after, which defines the function add_jitter. But it also complains, as "Ad_table_physical_filled.csv" does not exist.
<img width="1213" alt="image" src="https://github.com/paulhager/MMCL-Tabular-Imaging/assets/38837579/7162743a-7c04-4018-ab51-d525295e4674">

what might be relevant is another cell that loads "Ad table (extra).csv", but I don't know what this file is, and cannot find in DVM folder.  

<img width="1075" alt="image" src="https://github.com/paulhager/MMCL-Tabular-Imaging/assets/38837579/5e49d320-9b0c-4a0b-9aa4-27b2e95a0de2">

May I ask how can I handle this problem?

Thanks in advance,

Carrtesy

**Comment by paulhager** [comment]
Hi Carrtesy,

Ah, good catch, I've now moved that cell down to the very end, after the physical jittered files have been created.

The Ad table (extra) folder you can download along with the rest of the DVM data (https://figshare.com/articles/figure/DVM-CAR_Dataset/19586296/2)

Best,
Paul

**Comment by carrtesy** [comment]
Thanks for your answer.
But I still got a problem at the cell at the very end. are there any fix for it? 
<img width="1157" alt="image" src="https://github.com/paulhager/MMCL-Tabular-Imaging/assets/38837579/15957aab-5156-4558-8d53-5c736497eee2">

**Comment by paulhager** [comment]
ah, yeah I had multiple names for the files still in my folder. Sorry about that, I fixed it now.

**Comment by carrtesy** [comment]
Cool, all works well. Thanks for your help!

Best,
Carrtesy
