### ISSUE TITLE
Would you provide the config yaml file whose blanks are all filled ?

### ISSUE THREAD

**Issue by EMoonj** [paulhager/MMCL-Tabular-Imaging#11]
Thanks for your efforts to provide full code.
It's quite hard to deploy your code with pre-given config yaml file, because they are not fully filled. For example, hp.data_base is blank. Could you provide example config yaml file ?

**Comment by paulhager** [comment]
As explained in the README, "Path to folder containing data is set through the data_base argument and then joined with filenames set in the dataset yamls." You must set to this to the main folder containing all of the downloaded data on your machine. I cannot set this path for you.
