### ISSUE TITLE
[Errno 2] No such file or directory: 'data/DVM/features/train_paths_all_views.pt

### ISSUE THREAD

**Issue by carrtesy** [paulhager/MMCL-Tabular-Imaging#12]
Hello, I have question for running your code.

I've run the command:
```bash
python run.py pretrain=True datatype=multimodal checkpoint=checkpoints
```
And have encountered the following issue.
<img width="949" alt="image" src="https://github.com/paulhager/MMCL-Tabular-Imaging/assets/38837579/e8ef4e0e-607f-49a4-9eb0-3b4a5d1d8e17">
The error message says, we do not have "train_paths_all_views.pt" file. 
I've noticed that we only have two files, 

train_paths_all_views_server.pt  train_paths_all_views_tower.pt

the cell might be relevant is:
<img width="896" alt="image" src="https://github.com/paulhager/MMCL-Tabular-Imaging/assets/38837579/9ce3fbc7-952f-46f4-8e00-7954a65e0924">
And the whole datapreprocessing code, including cell does not save train_paths_all_views.pt.

May I ask how can I handle this problem?

I appreciate your help. 

Carrtesy

**Comment by paulhager** [comment]
The tower / server distinction is not relevant outside of my setup. Thanks showing me this, I've adjusted the code.

**Comment by Maria-2024-beep** [comment]
> Hello, I have question for running your code.
> 
> I've run the command:
> 
> ```shell
> python run.py pretrain=True datatype=multimodal checkpoint=checkpoints
> ```
> 
> And have encountered the following issue. <img alt="image" width="949" src="https://private-user-images.githubusercontent.com/38837579/278207088-e8ef4e0e-607f-49a4-9eb0-3b4a5d1d8e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTg0OTcsIm5iZiI6MTcyMTQxODE5NywicGF0aCI6Ii8zODgzNzU3OS8yNzgyMDcwODgtZThlZjRlMGUtNjA3Zi00OWE0LTllYjAtM2I0YTVkMWQ4ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5NDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTNhYjM2MGU4YWQ5NjZmZGU4ZGFhODBlYTA5M2RiMzIyMDg1N2U3OTcxMjVlNDkwNTEwYzI0OTNmYzA0OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UEOHpaTMy0d-Y_xS9XD47ineYroPSwWvAoXScifGhlI"> The error message says, we do not have "train_paths_all_views.pt" file. I've noticed that we only have two files,
> 
> train_paths_all_views_server.pt train_paths_all_views_tower.pt
> 
> the cell might be relevant is: <img alt="image" width="896" src="https://private-user-images.githubusercontent.com/38837579/278207449-9ce3fbc7-952f-46f4-8e00-7954a65e0924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTg0OTcsIm5iZiI6MTcyMTQxODE5NywicGF0aCI6Ii8zODgzNzU3OS8yNzgyMDc0NDktOWNlM2ZiYzctOTUyZi00NmY0LThlMDAtNzk1NGE2NWUwOTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5NDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlY2RiYjBjZmViYzc1ZTdhMzkzYTBiNWYxOWNkZTA3YTI4MzVhN2Q5NjQzYWFmYzI3MDBjNWZmOGU5NGZhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1h3OJK_vFwQucFjy9yXYAMuQ-os1wDxdX-pMKF7teag"> And the whole datapreprocessing code, including cell does not save train_paths_all_views.pt.
> 
> May I ask how can I handle this problem?
> 
> I appreciate your help.
> 
> Carrtesy

@carrtesy  would you please let me know how you solve this issue?
