### ISSUE TITLE
CMR data preprocessing

### ISSUE THREAD

**Issue by Yukui-1999** [paulhager/MMCL-Tabular-Imaging#13]
I am particularly interested in the preprocessing method for CMR images you mentioned in your paper, specifically the part where you stated, "The images used are two-channel 2D images whose channels are the middle baso-apical slice of the short axis cardiac MRI image at end-systolic and end-diastolic phases." In my experience with short axis CMR images, the number of slices varies between individuals due to differences in heart sizes, often ranging from 8 to 12 slices. I am curious about how you determined the middle baso-apical slice in your study.
I have contemplated a few approaches, such as consistently selecting the fourth or fifth slice or choosing the median slice number. However, I am keen to understand the methodology you employed in your research.
Or are you comfortable disclosing your data preprocessing code?
Thank you very much.

**Comment by paulhager** [comment]
You are correct that the number of slices varies from 8 to 12 depending on the individual. I just took the middle slice of each individual:

`mid_heart_slice = im[:,:,im.shape[2]//2]`
