### ISSUE TITLE
Environment Setup Issue

### ISSUE THREAD

**Issue by anikmuhury** [paulhager/MMCL-Tabular-Imaging#17]
Hello Hager,

Thank you for this awesome research work.
I have trouble configure the environment properly from the yaml file as some of the libraries are deprecated. Is it possible for you to share your environment as setup.exe file, so that I can mirror it.
I appreciate your help.
Thank you

**Comment by paulhager** [comment]
I don't have the environment required for this project setup anymore on our server. The most important dependencies for proper functioning are:
- pytorch=1.11.0
- pytorch-lightning=1.6.4
- torchmetrics=0.11.0
- lightning-bolts==0.5.0
- lightly==1.2.22

If you install those properly, I would just keep executing run.py and installing libraries as the import errors come up. Will be a bit annoying but should get you up and running within half an hour.
