### ISSUE TITLE
Testing Issue

### ISSUE THREAD

**Issue by subhrajitm20** [paulhager/MMCL-Tabular-Imaging#18]
Hi,

Thank You for your research work. I am having trouble in running `python test.py`. 
The test.py file contains `self.run_process(controller.control, args)`. 
So, did you have any separately written "Controller" file, that you have imported and have missed adding it in the repository, or is it a normal Python library? 
The environment.yaml file you have provided does not have any dependency on "controller". I tried `pip install controller` and run `python test.py` again, but then I am getting `Attribute Error: Module 'controller' has no attribute 'control'.`
So, is there some other python dependency that has controller.control in it?

I am done with the training part, and I am not able to proceed with the testing for a long time now. Can you please help me resolve this issue or provide me with a method to bypass this controller part, if possible.

Thank You for your help.

**Comment by paulhager** [comment]
Ah, yes I had a controller.py script that managed all of my experiments for me, but thats not relevant for the work so I removed it. The test.py file is also just unittests to make sure the code is working, its not used to test any results, so you can just ignore it.
