### ISSUE TITLE
dataset argument? where is it?

### ISSUE THREAD

**Issue by Christinaaa23** [paulhager/MMCL-Tabular-Imaging#22]
1+ Stars.

Very nice.

one problem:

![image](https://github.com/user-attachments/assets/0fe73616-6dde-4d33-a615-e06498f1d2b6)

why this error occurred?

which dataset argument it means?

please help me !

**Comment by paulhager** [comment]
That should be datatype, its a typo. Thanks for catching it, I've updated the file

**Comment by Christinaaa23** [comment]
> That should be datatype, its a typo. Thanks for catching it, I've updated the file

very well, but my problem is how I should call and set this argument to get rid of error?

**Comment by paulhager** [comment]
I recommend reading the ReadMe, it is explained there.
