### ISSUE TITLE
there is no val_images.pt?

### ISSUE THREAD

**Issue by Maria-2024-beep** [paulhager/MMCL-Tabular-Imaging#23]
in this code you write:

data/create_dvm_dataset.ipynb

![image](https://github.com/user-attachments/assets/0746a7a1-c49a-424a-acf6-8d3626f59b49)

are you sure about this file?  

Where this file should be created "val_images.pt"?

is there typo here?

Thanks for your help again

**Comment by paulhager** [comment]
This was from an old version where I had a subset of the images saved for examining the imaging transformations used. Its not relevant for training, you can ignore it or save some images yourself and specify the file there if you are curious.
