### ISSUE TITLE
Image Normalization

### ISSUE THREAD

**Issue by hk-zh** [paulhager/MMCL-Tabular-Imaging#24]
Thank you for this great contribution. I have a question regarding to the normalization of images. I found that in the notebook file [data/create_dvm_dataset.ipynb](https://github.com/paulhager/MMCL-Tabular-Imaging/blob/main/data/create_dvm_dataset.ipynb), you transform the value range from 0-255 to 0-1 by dividing 255. However, normally the image normalization process also include `image = (image - mean) / std `to make the image distribution have the mean value of 0 and the std of 1. 

Could I kindly ask if you have some special reasons for not doing that?

**Comment by paulhager** [comment]
No special reason, we tried z-normalization at the beginning but found empirically that it doesn't work as well as 0-1 normalization and its harder to some augmentations that cannot deal with negative numbers. 

Intuitively having a normal distribution can hurt performance because it removes some of the unique features and 0-1 distribution is enough for better training dynamics with lower pixel values

**Comment by hk-zh** [comment]
I think normally the z-normalization should be applied after all other data argumentations.
```
transform = transforms.Compose([
      transforms.RandomApply([transforms.ColorJitter(brightness=0.8, contrast=0.8, saturation=0.8)], p=0.8),
      transforms.RandomGrayscale(p=0.2),
      transforms.RandomApply([transforms.GaussianBlur(kernel_size=29, sigma=(0.1, 2.0))],p=0.5),
      transforms.RandomResizedCrop(size=(img_size,img_size), scale=(0.2, 1.0), ratio=(0.75, 1.3333333333333333)),
      transforms.RandomHorizontalFlip(p=0.5),
      transforms.Resize(size=(img_size,img_size)),
      transforms.toTensor()),
      transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
```
I tried the vanilla ResNet50 with the z-normalization in the DVM-CAR domain. I used the same data argumentation as you did. I found that it already reach very high performance 94% top-1 accuracy.

> No special reason, we tried z-normalization at the beginning but found empirically that it doesn't work as well as 0-1 normalization and its harder to some augmentations that cannot deal with negative numbers.
> 
> Intuitively having a normal distribution can hurt performance because it removes some of the unique features and 0-1 distribution is enough for better training dynamics with lower pixel values
