### ISSUE TITLE
from Utils import check_or_save

### ISSUE THREAD

**Issue by user4753** [paulhager/MMCL-Tabular-Imaging#5]
In the given code, the implementation of the check_or_save function is not provided. It appears that the code assumes the existence of the check_or_save function from an external module or file called "Utils". However, since the specific implementation of the function is not available in the provided code, it's not possible to determine how it is implemented without additional information or access to the "Utils" module.

**Comment by paulhager** [comment]
I've now added the code for this function to the nodebook.

**Comment by user4753** [comment]
Thank you, so much! I'm trying to reproduce your code, and I study Medical
Imaging and Contrastive Learning. So your paper is helpful for me, Thank
you!

2023년 7월 11일 (화) 오전 12:18, Paul Hager ***@***.***>님이 작성:
