### ISSUE TITLE
How to do image preprocessing

### ISSUE THREAD

**Issue by Ivygugu** [paulhager/MMCL-Tabular-Imaging#8]
Hi, 

I'm trying to use your network structure for pulmonary embolism detection based on CT images and electronic medical records, but I have some problems in the reproduction process:
1. Since I haven't got the UKBB dataset yet, I don't know the structure of the dataset, can you introduce how you deal with medical images and electronic medical records? What should their directory look like in code?
2. If the inputs are CT images and electronic medical records, how can I get the respective .py files?

Thanks！

**Comment by paulhager** [comment]
If you are loading images with a paths file (i.e. liveloading=False), it doesn't matter where the images are, you just need to have the correct paths in a .py file and set the flag. Take a look at the [dataset file](datasets/ContrastiveImagingAndTabularDataset.py).

If you are loading all images into RAM at once, create a list of tensors and then save them with torch.save.

For the tabular data, you just provide it as a CSV. The CSV cannot have missing values and should not have a header.
